# ------------------------ #
# WurmMapGen Configuration #
# ------------------------ #

serverName=[QC/FR/CAN] QBC Doriath |PVE | MODS 8 K 2025

# Chemins relatifs (fonctionnent sur Windows et Linux)
# Le robot cherche les bases de données dans le dossier ./sqlite/ que nous créons dans le workflow
dbDir=./sqlite/

# Nom des bases de données (assurez-vous qu'elles ont ces noms dans le dossier ./sqlite/)
zonesDb=wurmzones.db
itemsDb=wurmitems.db
playersDb=wurmplayers.db

# Configuration des dossiers de sortie
# Le robot générera tout dans le dossier courant (ce qui est idéal pour GitHub)
saveLocation=.

# Realtime (Désactivé pour GitHub car pas de PHP)
enableRealtimeMarkers=false
rmiHost=localhost
rmiPort=8080

# Map Display
# markerType 2 est parfait pour un affichage moderne
markerType=2

# Map Layers
showPlayers=false
showDeeds=true
showGuardTowers=true
showStructures=true
showPortals=true

# Map Generation
mapGeneratorThreads=2
mapTileSize=256
mapGenerateShading=true
mapShadingModifier=1.0
mapShadePaths=true
mapGenerateWater=true
mapGenerateBridges=true
