serverName=[QC/FR/CAN] QBC Doriath
wurmMapLocation=.
saveLocation=.
dbDir=./sqlite/
zonesDb=wurmzones.db
itemsDb=wurmitems.db
playersDb=wurmplayers.db

# Paramètres de la carte
actualMapSize=4096
mapTileSize=256
mapMaxZoom=5
mapMinZoom=0
nativeZoom=5
markerType=2

# Options activées
enableRealtimeMarkers=false
rmiHost=localhost
rmiPort=8080
