serverName=QBC Doriath 4K
wurmMapLocation=.
saveLocation=.
outputDataDir=./data/
outputTilesDir=./images/

verbose=true
forceRedraw=false

enableRealtimeMarkers=false
rmiHost=localhost
rmiPort=8080

markerType=2
showPlayers=false
showDeeds=true
showGuardTowers=true
showStructures=true
showPortals=true

mapGeneratorThreads=2
mapTileSize=256
mapGenerateShading=true
mapShadingModifier=1.0
mapShadePaths=true
mapGenerateWater=true
mapGenerateBridges=true
