name: Synchro Carte Wurm Legion Hosting

on:
  schedule:
    - cron: '0 4 * * *' # Étape automatique : S'exécute toutes les nuits à 4h00 UTC
  workflow_dispatch: # Étape manuelle : Ajoute le bouton gris pour forcer la mise à jour

permissions:
  contents: write # Donne le droit à GitHub d'enregistrer vos fichiers JSON

jobs:
  download-json:
    runs-on: ubuntu-latest
    steps:
    - name: 1. Connexion au depot GitHub
      uses: actions/checkout@v4
      with:
        persist-credentials: true

    - name: 2. Telechargement direct des fichiers de la carte (SFTP Port 2022)
      run: |
        sudo apt-get update && sudo apt-get install -y lftp
        mkdir -p ~/.lftp && echo "set sftp:auto-confirm yes; set ssl:verify-certificate false;" > ~/.lftp/rc
        
        # Le '|| true' à la fin empêche le script de planter si le dossier est vide
        lftp -u "${{ secrets.LEGION_USER }},${{ secrets.LEGION_PASS }}" sftp://${{ secrets.LEGION_HOST }}:${{ secrets.LEGION_PORT }} -e "
          lcd ./data;
          mget -O ./ *.json;
          bye
        " || true

    - name: 3. Sauvegarde et Envoi automatique sur GitHub
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@://github.com"
        
        # Force l'ajout des fichiers même s'ils n'ont pas bougé
        git add data/*.json || true
        
        # Enregistre les fichiers. S'il n'y a aucun changement, s'arrête proprement sans faire d'erreur
        git commit -m "Mise a jour automatique des fichiers de la carte [skip ci]" || exit 0
        git push origin main



